server:
  port: 8100

default:
  routingPolicies:
    - path: "/books/3"
      response:
        code: 200
        body: "Good"

    - path: "/books/1"
      params:
        number:
          - "1"
          - "2"
        isOn:
          - "on"
      filters:
        - type: "DelayFilter"
          args: |
            {
              "delayTime" : 2000,
              "deltaTime": 1000
            }
      response:
        code: 200
        body: "Param Good"

    - path: "/books/1"
      filters:
        - type: "DelayFilter"
          args: |
            {
              "delayTime" : 2000,
              "deltaTime": 1000
            }
      response:
        code: 200
        body: "no Param"

    - path: "/books/2"
      filters:
        - type: "HeaderFilter"
          args: |
            {
              "responseHeader" : "test"
            }
      response:
        code: 200
        body: |
          {
            "title" : "queen"
          }

    - path: "/test/404"
      response:
        code: 404
        body: "Not Found"

    - path: "/test/500"
      response:
        code: 500
        body: "Internal error"

    - path: "/test/ok"
      response:
        code: 200
        body: "ok"