
name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
    - id: gradle
      run: ./gradlew test
    - name: Report to CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.codecov_token }}
        file: ./build/reports/jacoco/test/html/index.html
