name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags: '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
    - id: gradle
      run: ./gradlew build
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.docker_hub_id }}
        password: ${{ secrets.docker_hub_token }}
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --tags `git rev-list --tags --max-count=1`)
    - name: Build the Docker image
      env:
        TAG: ${{ steps.get_version.outputs.VERSION }}
      run: docker build . --file Dockerfile --tag wenys/generalmock:${TAG} --build-arg JAR=$(ls build/libs/*.jar)
    - name: Push Docker image
      env:
        TAG: ${{ steps.get_version.outputs.VERSION }}
      run: docker push wenys/generalmock:${TAG}
