name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag generalmock:$(date +%s) --build-arg JAR=$(ls build/libs/*.jar)
