name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags: '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
    - id: gradle
      run: ./gradlew build
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.docker_hub_id }}
        password: ${{ secrets.docker_hub_token }}
    - name: Get the tag name
      run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wenys/generalmock:${TAG} --build-arg JAR=$(ls build/libs/*.jar)
    - name: Push Docker image
      run: docker push wenys/generalmock:${TAG}
